export const ALL_SUPPORT_TIME_FORMAT = [
  'YYYY-MM-DD hh:mm:ss',
  'YYYY-M-D hh:mm:ss',
  'YYYY-MM-DD hh:mm',
  'YYYY-M-D hh:mm',
  'YYYYMMDD',
  'YYYY-MM-DD',
  'YYYY-M-D',
  'YYYY/MM/DD',
  'YYYY/M/D',
  'YYYYMM',
  'YYYY-MM',
  'YYYY-M',
  'YYYY',
];
