// mock for @antv/gpt-vis used in tests to avoid ESM import issues
export enum ChartType {
  Area = 'Area',
  Bar = 'Bar',
  Boxplot = 'Boxplot',
  Column = 'Column',
  DualAxes = 'DualAxes',
  FishboneDiagram = 'FishboneDiagram',
  FlowDiagram = 'FlowDiagram',
  Funnel = 'Funnel',
  Histogram = 'Histogram',
  Line = 'Line',
  Liquid = 'Liquid',
  MindMap = 'MindMap',
  NetworkGraph = 'NetworkGraph',
  OrganizationChart = 'OrganizationChart',
  PathMap = 'PathMap',
  Pie = 'Pie',
  PinMap = 'PinMap',
  Radar = 'Radar',
  Sankey = 'Sankey',
  Scatter = 'Scatter',
  Treemap = 'Treemap',
  Venn = 'Venn',
  Violin = 'Violin',
  WordCloud = 'WordCloud',
}
