import { ChartKnowledgeBase } from './interface';

export const base: ChartKnowledgeBase = {
  single_line_chart: {
    id: 'single_line_chart',
    name: 'Single Line Chart',
    alias: ['Line', 'Line Chart', 'Basic Line Chart'],
    family: ['LineCharts'],
    def:
      'A single line chart is a chart that uses one line with segments to show changes in data in a ordinal dimension.',
    purpose: ['Trend'],
    coord: ['Cartesian2D'],
    category: ['Statistic'],
    shape: ['Lines'],
    dataPres: [
      { minQty: 1, maxQty: 1, fieldConditions: ['Time', 'Ordinal'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Interval'] },
    ],
    channel: ['Position', 'Direction'],
  },

  multi_line_chart: {
    id: 'multi_line_chart',
    name: 'Multi Line Chart',
    alias: ['Multi Line', 'Multi-Line', 'Multi-Line Chart', 'Lines'],
    family: ['LineCharts'],
    def:
      'A multi line chart is a chart that uses multiple lines with segments to show changes in data in a ordinal dimension.',
    purpose: ['Comparison', 'Trend'],
    coord: ['Cartesian2D'],
    category: ['Statistic'],
    shape: ['Lines'],
    dataPres: [
      { minQty: 1, maxQty: 1, fieldConditions: ['Time', 'Ordinal'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Nominal'] },
      { minQty: 2, maxQty: '*', fieldConditions: ['Interval'] },
    ],
    channel: ['Position', 'Direction'],
  },

  single_step_line_chart: {
    id: 'single_step_line_chart',
    name: 'Single Step Line Chart',
    alias: ['Step Line', 'Step Chart', 'Single Step Chart'],
    family: ['LineCharts'],
    def:
      'A single step line chart is a single line chart in which points are connected by horizontal and vertical line segments, looking like steps of a staircase.',
    purpose: ['Trend'],
    coord: ['Cartesian2D'],
    category: ['Statistic'],
    shape: ['Lines'],
    dataPres: [
      { minQty: 1, maxQty: 1, fieldConditions: ['Time', 'Ordinal'] },
      { minQty: 0, maxQty: 1, fieldConditions: ['Nominal'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Interval'] },
    ],
    channel: ['Position', 'Direction'],
  },

  multi_step_line_chart: {
    id: 'multi_step_line_chart',
    name: 'Multi Step Line Chart',
    alias: ['Step Lines', 'Multi Step Chart'],
    family: ['LineCharts'],
    def:
      'A step line chart is a multi line chart in which points of each line are connected by horizontal and vertical line segments, looking like steps of a staircase.',
    purpose: ['Comparison', 'Trend'],
    coord: ['Cartesian2D'],
    category: ['Statistic'],
    shape: ['Lines'],
    dataPres: [
      { minQty: 1, maxQty: 1, fieldConditions: ['Time', 'Ordinal'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Nominal'] },
      { minQty: 2, maxQty: '*', fieldConditions: ['Interval'] },
    ],
    channel: ['Position', 'Direction'],
  },

  basic_area_chart: {
    id: 'basic_area_chart',
    name: 'Basic Area Chart',
    alias: ['Area Chart', 'Single Area Chart'],
    family: ['AreaCharts'],
    def: 'A basic area chart uses a line segment with a filled area to show the change in data in a ordinal dimension.',
    purpose: ['Trend'],
    coord: ['Cartesian2D'],
    category: ['Statistic'],
    shape: ['Area'],
    dataPres: [
      { minQty: 1, maxQty: 1, fieldConditions: ['Time', 'Ordinal'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Interval'] },
    ],
    channel: ['Position'],
  },

  multi_color_area_chart: {
    id: 'multi_color_area_chart',
    name: 'Multi Color Area Chart',
    alias: ['Area Chart', 'Multi Area Chart', 'Overlap Area Chart'],
    family: ['AreaCharts'],
    def:
      'A multi color area chart uses series of line segments with overlapped areas to show the change in data in a ordinal dimension.',
    purpose: ['Comparison', 'Trend'],
    coord: ['Cartesian2D'],
    category: ['Statistic'],
    shape: ['Area'],
    dataPres: [
      { minQty: 1, maxQty: 1, fieldConditions: ['Time', 'Ordinal'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Interval'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Nominal'] },
    ],
    channel: ['Color', 'Position'],
  },

  stacked_area_chart: {
    id: 'stacked_area_chart',
    name: 'Stacked Area Chart',
    alias: [],
    family: ['AreaCharts'],
    def:
      'A stacked area chart uses layered line segments with different styles of padding regions to display how multiple sets of data change in the same ordinal dimension, and the endpoint heights of the segments on the same dimension tick are accumulated by value.',
    purpose: ['Comparison', 'Composition', 'Trend'],
    coord: ['Cartesian2D'],
    category: ['Statistic'],
    shape: ['Area'],
    dataPres: [
      { minQty: 1, maxQty: 1, fieldConditions: ['Time', 'Ordinal'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Interval'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Nominal'] },
    ],
    channel: ['Color', 'Length'],
  },

  percent_stacked_area_chart: {
    id: 'percent_stacked_area_chart',
    name: 'Percent Stacked Area Chart',
    alias: ['Percent Stacked Area', '% Stacked Area', '100% Stacked Area'],
    family: ['AreaCharts'],
    def:
      'A percent stacked area chart is an extented stacked area chart in which the height of the endpoints of the line segment on the same dimension tick is the accumulated proportion of the ratio, which is 100% of the total.',
    purpose: ['Comparison', 'Composition', 'Proportion', 'Trend'],
    coord: ['Cartesian2D'],
    category: ['Statistic'],
    shape: ['Area'],
    dataPres: [
      { minQty: 1, maxQty: 1, fieldConditions: ['Time', 'Ordinal'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Interval'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Nominal'] },
    ],
    channel: ['Color', 'Length'],
  },

  interval_area_chart: {
    id: 'interval_area_chart',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  stream_chart: {
    id: 'stream_chart',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  basic_column_chart: {
    id: 'basic_column_chart',
    name: 'Basic Column Chart',
    alias: ['Column', 'Column Chart', 'Single Color Column Chart'],
    family: ['ColumnCharts'],
    def:
      'A basic column chart uses columns to display the value of the dimension. The horizontal axis shows the classification dimension and the vertical axis shows the corresponding value.',
    purpose: ['Comparison', 'Distribution', 'Rank'],
    coord: ['Cartesian2D'],
    category: ['Statistic'],
    shape: ['Bars'],
    dataPres: [
      { minQty: 1, maxQty: 1, fieldConditions: ['Nominal'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Interval'] },
    ],
    channel: ['Position'],
  },

  multi_color_column_chart: {
    id: 'multi_color_column_chart',
    name: 'Multi Color Column Chart',
    alias: ['Column', 'Column Chart'],
    family: ['ColumnCharts'],
    def:
      'A multi color column chart uses series of columns to display the value of the dimension. The horizontal axis shows the classification dimension and the vertical axis shows the corresponding value.',
    purpose: ['Comparison', 'Distribution', 'Rank'],
    coord: ['Cartesian2D'],
    category: ['Statistic'],
    shape: ['Bars'],
    dataPres: [
      { minQty: 2, maxQty: 2, fieldConditions: ['Nominal'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Interval'] },
    ],
    channel: ['Position'],
  },

  grouped_column_chart: {
    id: 'grouped_column_chart',
    name: 'Grouped Column Chart',
    alias: ['Grouped Column'],
    family: ['ColumnCharts'],
    def:
      'A grouped column chart uses columns of different colors to form a group to display the values ​​of dimensions. The horizontal axis indicates the grouping of categories, the color indicates the categories, and the vertical axis shows the corresponding value.',
    purpose: ['Comparison', 'Distribution', 'Rank'],
    coord: ['Cartesian2D'],
    category: ['Statistic'],
    shape: ['Bars'],
    dataPres: [
      { minQty: 2, maxQty: 2, fieldConditions: ['Nominal'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Interval'] },
    ],
    channel: ['Color', 'Position'],
  },

  stacked_column_chart: {
    id: 'stacked_column_chart',
    name: 'Stacked Column Chart',
    alias: ['Stacked Column'],
    family: ['ColumnCharts'],
    def:
      'A stacked column chart uses stacked bars of different colors to display the values ​​for each dimension. The horizontal axis indicates the first classification dimension, the color indicates the second classification dimension, and the vertical axis shows the corresponding value.',
    purpose: ['Comparison', 'Composition', 'Distribution', 'Rank'],
    coord: ['Cartesian2D'],
    category: ['Statistic'],
    shape: ['Bars'],
    dataPres: [
      { minQty: 2, maxQty: 2, fieldConditions: ['Nominal'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Interval'] },
    ],
    channel: ['Color', 'Length', 'Position'],
  },

  percent_stacked_column_chart: {
    id: 'percent_stacked_column_chart',
    name: 'Percent Stacked Column Chart',
    alias: ['Percent Stacked Column', '% Stacked Column', '100% Stacked Column'],
    family: ['ColumnCharts'],
    def:
      'A percent stacked column chart uses stacked bars of different colors to display the values ​​for each dimension. The horizontal axis indicates the first classification dimension, the color indicates the second classification dimension, and the vertical axis shows the percentage of the corresponding classification.',
    purpose: ['Comparison', 'Composition', 'Distribution', 'Proportion'],
    coord: ['Cartesian2D'],
    category: ['Statistic'],
    shape: ['Bars'],
    dataPres: [
      { minQty: 2, maxQty: 2, fieldConditions: ['Nominal'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Interval'] },
    ],
    channel: ['Color', 'Length'],
  },

  interval_column_chart: {
    id: 'interval_column_chart',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  waterfall_chart: {
    id: 'waterfall_chart',
    name: 'Waterfall Chart',
    alias: ['Flying Bricks Chart', 'Mario Chart', 'Bridge Chart', 'Cascade Chart'],
    family: ['ColumnCharts'],
    def:
      'A waterfall chart is used to portray how an initial value is affected by a series of intermediate positive or negative values',
    purpose: ['Comparison', 'Trend'],
    coord: ['Cartesian2D'],
    category: ['Statistic'],
    shape: ['Bars'],
    dataPres: [
      { minQty: 1, maxQty: 1, fieldConditions: ['Ordinal', 'Time'] },
      { minQty: 2, maxQty: 2, fieldConditions: ['Interval'] },
    ],
    channel: ['Color', 'Length', 'Position'],
  },

  histogram: {
    id: 'histogram',
    name: 'Histogram',
    alias: [],
    family: ['ColumnCharts'],
    def: 'A histogram is an accurate representation of the distribution of numerical data.',
    purpose: ['Distribution'],
    coord: ['Cartesian2D'],
    category: ['Statistic'],
    shape: ['Bars'],
    dataPres: [{ minQty: 1, maxQty: 1, fieldConditions: ['Interval'] }],
    channel: ['Position'],
  },

  basic_bar_chart: {
    id: 'basic_bar_chart',
    name: 'Basic Bar Chart',
    alias: ['Bar', 'Bar Chart', 'Single Color Bar Chart'],
    family: ['BarCharts'],
    def:
      'A basic bar chart uses bars to display the value of the dimension. The vertical axis shows the classification dimension and the horizontal axis shows the corresponding value.',
    purpose: ['Comparison', 'Distribution', 'Rank'],
    coord: ['Cartesian2D'],
    category: ['Statistic'],
    shape: ['Bars'],
    dataPres: [
      { minQty: 1, maxQty: 1, fieldConditions: ['Nominal'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Interval'] },
    ],
    channel: ['Position'],
  },

  multi_color_bar_chart: {
    id: 'multi_color_bar_chart',
    name: 'Multi Color Bar Chart',
    alias: ['Bar', 'Bar Chart'],
    family: ['BarCharts'],
    def:
      'A multi color bar chart uses series of bars to display the value of the dimension. The vertical axis shows the classification dimension and the horizontal axis shows the corresponding value.',
    purpose: ['Comparison', 'Distribution', 'Rank'],
    coord: ['Cartesian2D'],
    category: ['Statistic'],
    shape: ['Bars'],
    dataPres: [
      { minQty: 2, maxQty: 2, fieldConditions: ['Nominal'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Interval'] },
    ],
    channel: ['Position'],
  },

  grouped_bar_chart: {
    id: 'grouped_bar_chart',
    name: 'Grouped Bar Chart',
    alias: ['Grouped Bar'],
    family: ['BarCharts'],
    def:
      'A grouped bar chart uses bars of different colors to form a group to display the values of the dimensions. The vertical axis indicates the grouping of categories, the color indicates the categories, and the horizontal axis shows the corresponding value.',
    purpose: ['Comparison', 'Distribution', 'Rank'],
    coord: ['Cartesian2D'],
    category: ['Statistic'],
    shape: ['Bars'],
    dataPres: [
      { minQty: 2, maxQty: 2, fieldConditions: ['Nominal'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Interval'] },
    ],
    channel: ['Color', 'Position'],
  },

  stacked_bar_chart: {
    id: 'stacked_bar_chart',
    name: 'Stacked Bar Chart',
    alias: ['Stacked Bar'],
    family: ['BarCharts'],
    def:
      'A stacked bar chart uses stacked bars of different colors to display the values ​​for each dimension. The vertical axis indicates the first classification dimension, the color indicates the second classification dimension, and the horizontal axis shows the corresponding value.',
    purpose: ['Comparison', 'Composition', 'Distribution', 'Rank'],
    coord: ['Cartesian2D'],
    category: ['Statistic'],
    shape: ['Bars'],
    dataPres: [
      { minQty: 2, maxQty: 2, fieldConditions: ['Nominal'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Interval'] },
    ],
    channel: ['Color', 'Length', 'Position'],
  },

  percent_stacked_bar_chart: {
    id: 'percent_stacked_bar_chart',
    name: 'Percent Stacked Bar Chart',
    alias: ['Percent Stacked Bar', '% Stacked Bar', '100% Stacked Bar'],
    family: ['BarCharts'],
    def:
      'A percent stacked column chart uses stacked bars of different colors to display the values ​​for each dimension. The vertical axis indicates the first classification dimension, the color indicates the second classification dimension, and the horizontal axis shows the percentage of the corresponding classification.',
    purpose: ['Comparison', 'Composition', 'Distribution', 'Proportion'],
    coord: ['Cartesian2D'],
    category: ['Statistic'],
    shape: ['Bars'],
    dataPres: [
      { minQty: 2, maxQty: 2, fieldConditions: ['Nominal'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Interval'] },
    ],
    channel: ['Color', 'Length'],
  },

  interval_bar_chart: {
    id: 'interval_bar_chart',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  radial_bar_chart: {
    id: 'radial_bar_chart',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  mirror_bar_chart: {
    id: 'mirror_bar_chart',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  basic_pie_chart: {
    id: 'basic_pie_chart',
    name: 'Pie Chart',
    alias: ['Circle Chart', 'Pie'],
    family: ['PieCharts'],
    def:
      'A pie chart is a chart that the classification and proportion of data are represented by the color and arc length (angle, area) of the sector.',
    purpose: ['Comparison', 'Composition', 'Proportion'],
    coord: ['Polar'],
    category: ['Statistic'],
    shape: ['Round'],
    dataPres: [
      { minQty: 1, maxQty: 1, fieldConditions: ['Nominal'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Interval'] },
    ],
    channel: ['Angle', 'Area', 'Color'],
  },

  donut_chart: {
    id: 'donut_chart',
    name: 'Donut Chart',
    alias: ['Donut', 'Doughnut', 'Doughnut Chart'],
    family: ['PieCharts'],
    def:
      'A donut chart is a variation on a Pie chart except it has a round hole in the center which makes it look like a donut.',
    purpose: ['Comparison', 'Composition', 'Proportion'],
    coord: ['Polar'],
    category: ['Statistic'],
    shape: ['Round'],
    dataPres: [
      { minQty: 1, maxQty: 1, fieldConditions: ['Nominal'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Interval'] },
    ],
    channel: ['ArcLength'],
  },

  nested_pie_chart: {
    id: 'nested_pie_chart',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  nightingale_chart: {
    id: 'nightingale_chart',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  basic_scatter_plot: {
    id: 'basic_scatter_plot',
    name: 'Basic Scatter Plot',
    alias: ['Scatter Chart', 'Scatterplot'],
    family: ['ScatterCharts'],
    def:
      'A basic scatter plot is a type of plot or mathematical diagram using Cartesian coordinates to display values for typically two variables for a set of data.',
    purpose: ['Distribution'],
    coord: ['Cartesian2D'],
    category: ['Statistic'],
    shape: ['Scatter'],
    dataPres: [{ minQty: 2, maxQty: 2, fieldConditions: ['Interval'] }],
    channel: ['Position'],
  },

  multi_color_scatter_plot: {
    id: 'multi_color_scatter_plot',
    name: 'Multi Color Scatter Plot',
    alias: ['Scatter Chart', 'Scatterplot'],
    family: ['ScatterCharts'],
    def:
      'A multi color scatter plot is a type of plot or mathematical diagram using Cartesian coordinates to display values for typically two variables for series of data.',
    purpose: ['Comparison', 'Distribution'],
    coord: ['Cartesian2D'],
    category: ['Statistic'],
    shape: ['Scatter'],
    dataPres: [
      { minQty: 2, maxQty: 2, fieldConditions: ['Interval'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Nominal'] },
    ],
    channel: ['Color', 'Position'],
  },

  basic_bubble_chart: {
    id: 'basic_bubble_chart',
    name: 'Basic Bubble Chart',
    alias: ['Bubble Chart'],
    family: ['ScatterCharts'],
    def:
      'A basic bubble chart is a type of chart that displays three dimensions of data with x, y positions and circle size.',
    purpose: ['Comparison', 'Distribution'],
    coord: ['Cartesian2D'],
    category: ['Statistic'],
    shape: ['Scatter'],
    dataPres: [{ minQty: 3, maxQty: 3, fieldConditions: ['Interval'] }],
    channel: ['Position', 'Size'],
  },

  multi_color_bubble_chart: {
    id: 'multi_color_bubble_chart',
    name: 'Multi Color Bubble Chart',
    alias: ['Bubble Chart'],
    family: ['ScatterCharts'],
    def:
      'A multi color bubble chart is a type of chart that displays four dimensions of data with x, y positions, circle size and circle color.',
    purpose: ['Comparison', 'Distribution'],
    coord: ['Cartesian2D'],
    category: ['Statistic'],
    shape: ['Scatter'],
    dataPres: [
      { minQty: 3, maxQty: 3, fieldConditions: ['Interval'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Nominal'] },
    ],
    channel: ['Color', 'Position', 'Size'],
  },

  non_ribbon_chord_diagram: {
    id: 'non_ribbon_chord_diagram',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  arc_diagram: {
    id: 'arc_diagram',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  chord_diagram: {
    id: 'chord_diagram',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  treemap: {
    id: 'treemap',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  sankey_diagram: {
    id: 'sankey_diagram',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  basic_funnel_chart: {
    id: 'basic_funnel_chart',
    name: 'Basic Funnel Chart',
    alias: [],
    family: ['FunnelCharts'],
    def:
      'A basic funnel chart is often used to represent stages in a sales process and show the amount of potential revenue for each stage.',
    purpose: ['Trend'],
    coord: ['SymmetricCartesian'],
    category: ['Statistic'],
    shape: ['Symmetric'],
    dataPres: [
      { minQty: 1, maxQty: 1, fieldConditions: ['Ordinal'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Interval'] },
    ],
    channel: ['Color', 'Length'],
  },

  overlapping_funnel_chart: {
    id: 'overlapping_funnel_chart',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  mirror_funnel_chart: {
    id: 'mirror_funnel_chart',
    name: 'Mirror Funnel Chart',
    alias: ['Contrast Funnel Chart'],
    family: ['FunnelCharts'],
    def: 'A mirror funnel chart is a funnel chart divided into two series by a central axis.',
    purpose: ['Comparison', 'Trend'],
    coord: ['SymmetricCartesian'],
    category: ['Statistic'],
    shape: ['Symmetric'],
    dataPres: [
      { minQty: 1, maxQty: 1, fieldConditions: ['Ordinal'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Interval'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Nominal'] },
    ],
    channel: ['Color', 'Length', 'Direction'],
  },

  boxplot: {
    id: 'boxplot',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  heatmap: {
    id: 'heatmap',
    name: 'Heatmap',
    alias: ['Heat Map'],
    family: ['HeatmapCharts'],
    def:
      'A heat map is a graphical representation of data where the individual values contained in a matrix are represented as colors.',
    purpose: ['Distribution'],
    coord: ['Cartesian2D'],
    category: ['Statistic'],
    shape: ['Square'],
    dataPres: [
      { minQty: 2, maxQty: 2, fieldConditions: ['Nominal', 'Ordinal'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Interval'] },
    ],
    channel: ['Color', 'Position'],
  },

  gauge_chart: {
    id: 'gauge_chart',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  basic_radar_chart: {
    id: 'basic_radar_chart',
    name: 'Basic Radar Chart',
    alias: ['Web Chart', 'Spider Chart', 'Star Chart', 'Cobweb Chart', 'Irregular Polygon', 'Kiviat diagram'],
    family: ['RadarCharts'],
    def:
      'A basic radar chart maps the data volume of multiple dimensions onto the axes. Starting at the same center point, usually ending at the edge of the circle, connecting the same set of points using lines.',
    purpose: ['Comparison'],
    coord: ['Radar'],
    category: ['Statistic'],
    shape: ['Round'],
    dataPres: [
      { minQty: 1, maxQty: '*', fieldConditions: ['Nominal'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Interval'] },
    ],
    channel: ['Color', 'Position'],
  },

  multi_color_radar_chart: {
    id: 'multi_color_radar_chart',
    name: 'Multi Color Radar Chart',
    alias: ['Web Chart', 'Spider Chart', 'Star Chart', 'Cobweb Chart', 'Irregular Polygon', 'Kiviat diagram'],
    family: ['RadarCharts'],
    def:
      'A multi color radar chart maps series of data volume of multiple dimensions onto the axes. Starting at the same center point, usually ending at the edge of the circle, connecting the same set of points using lines.',
    purpose: ['Comparison'],
    coord: ['Radar'],
    category: ['Statistic'],
    shape: ['Round'],
    dataPres: [
      { minQty: 1, maxQty: '*', fieldConditions: ['Nominal'] },
      { minQty: 1, maxQty: 1, fieldConditions: ['Interval'] },
    ],
    channel: ['Color', 'Position'],
  },

  wordcloud: {
    id: 'wordcloud',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  candlestick_chart: {
    id: 'candlestick_chart',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  compact_box_tree: {
    id: 'compact_box_tree',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  dendrogram: {
    id: 'dendrogram',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  indented_tree: {
    id: 'indented_tree',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  radial_tree: {
    id: 'radial_tree',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  flow_diagram: {
    id: 'flow_diagram',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  fruchterman_layout_cluster_graph: {
    id: 'fruchterman_layout_cluster_graph',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  fruchterman_layout_graph: {
    id: 'fruchterman_layout_graph',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  force_directed_layout_graph: {
    id: 'force_directed_layout_graph',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  circular_layout_graph: {
    id: 'circular_layout_graph',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  spiral_layout_graph: {
    id: 'spiral_layout_graph',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  radial_layout_graph: {
    id: 'radial_layout_graph',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  concentric_layout_graph: {
    id: 'concentric_layout_graph',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  grid_layout_graph: {
    id: 'grid_layout_graph',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  bubbles_diagram: {
    id: 'bubbles_diagram',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  symbol_map: {
    id: 'symbol_map',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  chart_map: {
    id: 'chart_map',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  column_map_3d: {
    id: 'column_map_3d',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  scatter_map: {
    id: 'scatter_map',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  path_map: {
    id: 'path_map',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  isoline_map: {
    id: 'isoline_map',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  arc_map_3d: {
    id: 'arc_map_3d',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  choropleth_map: {
    id: 'choropleth_map',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  choropleth_map_3d: {
    id: 'choropleth_map_3d',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  hexagonal_heat_map: {
    id: 'hexagonal_heat_map',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  hexagonal_heat_map_3d: {
    id: 'hexagonal_heat_map_3d',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  classical_heat_map: {
    id: 'classical_heat_map',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  grid_heat_map: {
    id: 'grid_heat_map',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  packed_circles: {
    id: 'packed_circles',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  polar_treemap: {
    id: 'polar_treemap',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },

  sunburst_diagram: {
    id: 'sunburst_diagram',
    name: '',
    alias: [],
    family: [],
    def: '',
    purpose: [],
    coord: [],
    category: [],
    shape: [],
    dataPres: [],
    channel: [],
  },
};
